apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mirrord-demo
  namespace: staging
  labels:
    app: ai-mirrord-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-mirrord-demo
  template:
    metadata:
      labels:
        app: ai-mirrord-demo
    spec:
      containers:
      - name: ai-mirrord-demo
        image: ai-mirrord-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # Production database configuration (different from local)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: connection-string
        # Production Redis configuration (different from what AI assumes)
        - name: REDIS_CLUSTER_HOST
          value: "redis-cluster.staging.svc.cluster.local"
        - name: REDIS_CLUSTER_PORT
          value: "6379"
        - name: REDIS_CLUSTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        # External API configuration
        - name: EXTERNAL_API_URL
          value: "https://api.production.example.com"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-key
        # JWT configuration
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-mirrord-demo-service
  namespace: staging
spec:
  selector:
    app: ai-mirrord-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP 